api_platform:
    title: 'GestAsso API'
    description: 'API de gestion de clubs sportifs'
    version: '1.0.0'
    # Activer le support des contrôleurs Symfony personnalisés avec annotations OpenAPI
    use_symfony_listeners: true
    # Forcer l'inclusion des contrôleurs personnalisés avec annotations OpenAPI
    mapping:
        paths:
            - '%kernel.project_dir%/src/Controller'
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    enable_swagger_ui: true
    enable_re_doc: true
    enable_docs: true
    docs_formats:
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']
    swagger:
        versions: [3]
        api_keys:
            JWT:
                name: Authorization
                type: header
    openapi:
        contact:
            name: 'Support GestAsso'
            email: 'support@gestasso.com'
        license:
            name: 'Propriétaire'
