vich_uploader:
    db_driver: orm
    
    mappings:
        documents:
            uri_prefix: /uploads/documents
            upload_destination: '%kernel.project_dir%/public/uploads/documents'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            
        club_images:
            uri_prefix: /uploads/clubs
            upload_destination: '%kernel.project_dir%/public/uploads/clubs'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            
        team_images:
            uri_prefix: /uploads/teams
            upload_destination: '%kernel.project_dir%/public/uploads/teams'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            
        event_images:
            uri_prefix: /uploads/events
            upload_destination: '%kernel.project_dir%/public/uploads/events'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer 